<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_theme_suggestions_form_alter().
 */
function pettys_alter_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  if (isset($variables['element']['#form_id'])) {
    $form_id = $variables['element']['#form_id'];
    if ($form_id == 'commerce_currency_resolver_select_form') {
      // $suggestions[] = 'form__contact_feedback';
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function pettys_alter_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'commerce_currency_resolver_select_form') {
    $form['currency']['#attributes']['class'] = ["select-custom"];
  }

  // Form search.
  if ($form_id == 'search_block_form') {
    $form['keys']['#attributes']['placeholder'] = "Search";
    unset($form['actions']['submit']);
  }

  // Form newsletter.
  if ($form_id == 'simplenews_subscriptions_block_916b8eee-678f-476c-94a9-41cb258c713f') {
    unset($form['mail']["widget"][0]['value']['#title']);
    unset($form['mail']["widget"][0]['value']['#description']);
    $form['mail']["widget"][0]['value']['#attributes']['placeholder'] = "Enter your email";
    unset($form['mail']["widget"][0]['value']['#prefix']);
    $form['actions']["submit"]['#value'] = t("Send");
    $form['actions']["submit"]['#attributes']['class'] = ["btn", "btn-newsletter"];
  }
}

/**
 * Implements hook_theme_suggestions_form_element().
 */
function pettys_alter_theme_suggestions_form_element_alter(array &$suggestions, array $variables) {
    // dump($variables);
    // $suggestions[] = 'form_element__type__' . $variables['element']['#type'];

    // if (isset($variables['element']['#form_id'])) {
    //     $suggestions[] = 'form_element__form_id__' . $variables['element']['#form_id'];
    //     $suggestions[] = 'form_element__' . $variables['element']['#form_id'] . '__' . $variables['element']['#type'];
    // }
}

/**
 * Implements hook_preprocess_menu().
 */
function pettys_alter_preprocess_menu__account(&$variables) {
  $current_user = \Drupal::currentUser();
  if ($current_user->isAnonymous()) {
    // Alter text login link.
    // $url = Url::fromRoute('user.login');
    // $internal_link = Link::fromTextAndUrl(t('Sign in'), $url)->toString();
    // $variables['items']['user.logout']['title'] = $internal_link;

    $variables['items']['user.logout']['title'] = t("Sign in"); // $internal_link;

    // // add sign up link.
    $url_signup = Url::fromRoute('user.register');
    // $signup_link = Link::fromTextAndUrl(t('Sign up'), $url_signup)->toString();
    $variables['items']['user.user'] = [
      'title' => t("Sign up"),
      'url' => $url_signup,
      'route_name' => 'user.register',
      'parent' => 'main',
      'weight' => 0
    ];
  }
}

/**
 * Implements hook_theme().
 */
function pettys_alter_theme($existing, $type, $theme, $path) {
  return [
    'pettys_alter_commerce_currency_resolver_select_form' => [
      'variables' => [
        'render element' => 'form',
        'template' => 'pettys-alter-commerce-currency-resolver-select-form',
        'form' => NULL,
        'form_id' => NULL,
        'form_elements' => [],
      ],
    ],
    'form__contact_feedback' => [
      'variables' => [
        'template' => 'form--contact-feedback',
      ],
    ],
  ];
}

